# Produce formatted tables for Annex 5

In [33]:
import numpy as np
import pandas as pd
from ar6.utils import mkdir_p

In [34]:
mkdir_p('../data_output/annex5/')

In [29]:
years = [2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100, 2200, 2300, 2400, 2500]
years_hist = [1750, 1850, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015, 2019]

In [42]:
scenarios_ssp = ['ssp119','ssp126','ssp245','ssp370','ssp370-lowNTCF-gidden','ssp370-lowNTCF-aerchemmip','ssp434','ssp460','ssp534-over','ssp585']
scenarios_rcp = ['rcp26', 'rcp45', 'rcp60', 'rcp85']
erf = {}
for scenario in scenarios_ssp:
    erf[scenario] = pd.read_csv('../data_output/SSPs/ERF_%s_1750-2500.csv' % scenario, index_col=0)
    erf[scenario].loc[years,:].to_csv('../data_output/annex5/ERF_%s_2020-2500.csv' % scenario, float_format='%.2f')
for scenario in scenarios_rcp:
    erf[scenario] = pd.read_csv('../data_output/RCPs/ERF_%s_1750-2500.csv' % scenario, index_col=0)
erf['historical'] = pd.read_csv('../data_output/AR6_ERF_1750-2019.csv', index_col=0)
erf['historical'].drop(columns=['nonco2_wmghg','aerosol','chapter2_other_anthro'], inplace=True)
pd.options.display.float_format = "{:,.2f}".format

In [31]:
erf['historical'].loc[years_hist,:]

,co2,ch4,n2o,other_wmghg,o3,h2o_stratospheric,contrails,aerosol-radiation_interactions,aerosol-cloud_interactions,bc_on_snow,land_use,volcanic,solar,total_anthropogenic,total_natural,total
year,,,,,,,,,,,,,,,,
1750,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.20,0.10,0.00,0.30,0.30
1850,0.14,0.05,0.01,0.00,0.03,0.00,0.00,-0.01,-0.07,0.01,-0.03,0.19,0.01,0.13,0.20,0.33
1900,0.35,0.12,0.03,0.00,0.08,0.01,0.00,-0.06,-0.29,0.02,-0.08,0.20,-0.04,0.18,0.16,0.34
1910,0.41,0.15,0.04,0.00,0.09,0.01,0.00,-0.10,-0.42,0.03,-0.10,0.20,-0.02,0.12,0.18,0.30
1920,0.50,0.17,0.05,0.00,0.10,0.02,0.00,-0.10,-0.43,0.03,-0.11,0.19,0.01,0.23,0.20,0.43
1930,0.54,0.20,0.06,0.00,0.12,0.02,0.00,-0.11,-0.46,0.03,-0.13,0.19,0.02,0.26,0.21,0.48
1940,0.62,0.22,0.06,0.00,0.14,0.02,0.00,-0.15,-0.52,0.03,-0.14,0.19,0.04,0.29,0.23,0.52
1950,0.65,0.24,0.07,0.01,0.17,0.02,0.00,-0.15,-0.55,0.03,-0.14,0.18,0.06,0.35,0.24,0.59
1960,0.71,0.29,0.08,0.03,0.22,0.03,0.01,-0.25,-0.73,0.04,-0.17,0.18,0.09,0.26,0.27,0.54
1970,0.85,0.36,0.09,0.08,0.28,0.03,0.02,-0.38,-0.92,0.05,-0.18,0.05,0.08,0.29,0.13,0.42
1980,1.09,0.43,0.11,0.20,0.33,0.04,0.02,-0.41,-1.04,0.06,-0.18,0.09,0.11,0.66,0.19,0.86
1990,1.33,0.49,0.13,0.33,0.36,0.04,0.03,-0.38,-1.05,0.07,-0.19,0.14,0.11,1.17,0.24,1.42
2000,1.56,0.51,0.16,0.37,0.40,0.05,0.04,-0.30,-0.92,0.07,-0.19,0.18,0.11,1.74,0.29,2.02
2010,1.85,0.52,0.18,0.39,0.44,0.05,0.04,-0.27,-0.99,0.08,-0.20,0.14,-0.01,2.10,0.13,2.23
2015,2.01,0.53,0.20,0.40,0.47,0.05,0.05,-0.23,-0.89,0.08,-0.20,0.11,0.03,2.47,0.14,2.61
2019,2.16,0.54,0.21,0.41,0.47,0.05,0.06,-0.22,-0.84,0.08,-0.20,0.14,-0.02,2.72,0.12,2.84

In [32]:
erf['ssp119'].loc[years,:]

,co2,ch4,n2o,other_wmghg,o3,h2o_stratospheric,contrails,aerosol-radiation_interactions,aerosol-cloud_interactions,bc_on_snow,land_use,volcanic,solar,total_anthropogenic,total_natural,total
year,,,,,,,,,,,,,,,,
2020,2.22,0.55,0.21,0.40,0.42,0.05,0.05,-0.20,-0.81,0.08,-0.20,0.06,-0.02,2.77,0.04,2.81
2030,2.49,0.52,0.23,0.38,0.25,0.05,0.03,-0.16,-0.39,0.03,-0.21,0.00,-0.02,3.22,-0.02,3.20
2040,2.56,0.44,0.24,0.32,0.19,0.04,0.02,-0.16,-0.28,0.02,-0.21,0.00,-0.01,3.18,-0.01,3.18
2050,2.53,0.37,0.25,0.27,0.14,0.03,0.02,-0.17,-0.20,0.01,-0.21,0.00,0.01,3.04,0.01,3.05
2060,2.45,0.31,0.26,0.23,0.12,0.03,0.01,-0.17,-0.16,0.01,-0.21,0.00,0.01,2.87,0.01,2.88
2070,2.35,0.27,0.26,0.21,0.11,0.02,0.01,-0.16,-0.13,0.00,-0.20,0.00,0.02,2.74,0.02,2.76
2080,2.23,0.24,0.27,0.19,0.09,0.02,0.01,-0.15,-0.09,0.00,-0.19,0.00,0.02,2.62,0.02,2.64
2090,2.09,0.21,0.28,0.17,0.09,0.02,0.01,-0.14,-0.05,0.00,-0.19,0.00,0.01,2.48,0.01,2.48
2100,1.92,0.18,0.28,0.15,0.08,0.02,0.01,-0.13,-0.01,-0.00,-0.18,0.00,-0.00,2.33,-0.00,2.33
2200,1.16,0.12,0.32,0.07,0.06,0.01,0.00,-0.10,0.08,-0.01,-0.17,0.00,0.03,1.55,0.03,1.58
2300,1.14,0.09,0.31,0.04,0.03,0.01,0.00,-0.09,0.14,-0.01,-0.17,0.00,0.00,1.49,0.00,1.49
2400,1.09,0.09,0.30,0.03,0.03,0.01,0.00,-0.09,0.14,-0.01,-0.17,0.00,0.00,1.42,0.00,1.42
2500,1.05,0.09,0.30,0.02,0.03,0.01,0.00,-0.09,0.14,-0.01,-0.17,0.00,0.00,1.38,0.00,1.38

In [43]:
scenarios = scenarios_rcp + scenarios_ssp

In [50]:
data_output = []
for scenario in scenarios:
    data_output.append([
        scenario,
        erf[scenario].loc[2030,'total_anthropogenic'],
        erf[scenario].loc[2030,'total_natural'],
        erf[scenario].loc[2030,'total'],
        erf[scenario].loc[2050,'total_anthropogenic'],
        erf[scenario].loc[2050,'total_natural'],
        erf[scenario].loc[2050,'total'],
        erf[scenario].loc[2090,'total_anthropogenic'],
        erf[scenario].loc[2090,'total_natural'],
        erf[scenario].loc[2090,'total']
    ])
df = pd.DataFrame(data_output, columns = ['scenario','2030a','2030n','2030','2050a','2050n','2050','2090a','2090n','2090'])
df.set_index('scenario',inplace=True)
df.to_csv('../data_output/annex5/comparison.csv')

In [51]:
df

,2030a,2030n,2030,2050a,2050n,2050,2090a,2090n,2090
scenario,,,,,,,,,
rcp26,2.85,-0.02,2.83,3.11,0.01,3.12,2.70,0.01,2.71
rcp45,3.01,-0.02,2.99,3.90,0.01,3.91,4.48,0.01,4.49
rcp60,2.84,-0.02,2.82,3.56,0.01,3.58,5.51,0.01,5.52
rcp85,3.36,-0.02,3.34,5.01,0.01,5.03,8.46,0.01,8.46
ssp119,3.22,-0.02,3.20,3.04,0.01,3.05,2.48,0.01,2.48
ssp126,3.23,-0.02,3.21,3.56,0.01,3.58,3.24,0.01,3.25
ssp245,3.25,-0.02,3.24,4.23,0.01,4.24,5.32,0.01,5.33
ssp370,3.33,-0.02,3.31,4.61,0.01,4.63,7.43,0.01,7.44
ssp370-lowNTCF-gidden,3.26,-0.02,3.24,4.26,0.01,4.27,6.59,0.01,6.60
ssp370-lowNTCF-aerchemmip,3.40,-0.02,3.38,4.91,0.01,4.92,7.73,0.01,7.74
ssp434,3.26,-0.02,3.24,3.90,0.01,3.91,4.18,0.01,4.19
ssp460,3.31,-0.02,3.30,4.44,0.01,4.46,6.12,0.01,6.13
ssp534-over,3.62,-0.02,3.60,5.04,0.01,5.05,3.93,0.01,3.93
ssp585,3.61,-0.02,3.59,5.29,0.01,5.30,9.18,0.01,9.19